-- CREO SCHEMA EN CASO DE QUE NO EXISTA
CREATE DATABASE IF NOT EXISTS INVESTTRACK;
USE INVESTTRACK;

-- TABLAS BASE
CREATE TABLE IF NOT EXISTS USUARIOS(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS BROKERS(
	ID_BROKER INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    COMISION_ESTANDAR DECIMAL(5,2)
);
CREATE TABLE IF NOT EXISTS MONEDA(
	ID_MONEDA INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(3) NOT NULL,
    DESCRIPCION VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS SECTORES(
	ID_SECTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL
);
-- TABLAS DEPENDIENTES
CREATE TABLE IF NOT EXISTS ACTIVOS(
	ID_ACTIVO INT PRIMARY KEY AUTO_INCREMENT,
    TICKER VARCHAR(10),
    NOMBRE VARCHAR(30),
    ID_SECTOR INT,
    CONSTRAINT FK_ACTIVO_SECTOR FOREIGN KEY (ID_SECTOR) REFERENCES SECTORES(ID_SECTOR)
);
CREATE TABLE IF NOT EXISTS ORDENES_COMPRA_VENTA(
	ID_ORDEN INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ACTIVO INT,
    ID_BROKER INT,
    ID_MONEDA INT,
    CANTIDAD DECIMAL(15,2) NOT NULL,
    PRECIO_UNITARIO DECIMAL(15,2) NOT NULL,
    FECHA_OPERACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDEN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_ORDEN_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO),
    CONSTRAINT FK_ORDEN_BROKER FOREIGN KEY (ID_BROKER) REFERENCES BROKERS(ID_BROKER),
    CONSTRAINT FK_ORDEN_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID_MONEDA)
);
CREATE TABLE IF NOT EXISTS CAUCIONES_OPERADAS(
	ID_CAUCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    MONTO_COLOCADO DECIMAL(15,2) NOT NULL,
    TASA_NOMINAL_ANUAL DECIMAL(3,2) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    CONSTRAINT FK_CAUCION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
CREATE TABLE IF NOT EXISTS DIVIDENDOS_CUPONES(
	ID_RENTA INT PRIMARY KEY AUTO_INCREMENT, 
    ID_ACTIVO INT,
    MONTO_BRUTO DECIMAL(15,2) NOT NULL,
    IMPUESTOS DECIMAL(15,2) DEFAULT 0,
    MONTO_NETO DECIMAL(15,2) NOT NULL,
    FECHA_COBRO DATE NOT NULL,
    CONSTRAINT FK_RENTA_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);
CREATE TABLE IF NOT EXISTS COTIZACIONES_HISTORICAS(
	ID_PRECIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ACTIVO INT,
    PRECIO_CIERRE DECIMAL(15,2) NOT NULL,
    FECHA_PRECIO DATE NOT NULL,
    CONSTRAINT FK_COTIZACION_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);
CREATE TABLE PORTFOLIO(
	ID_PORTFOLIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ACTIVO INT, 
    CANTIDAD_TOTAL DECIMAL(15,2),
    ULTIMO_PRECIO DECIMAL(15,2),
    CONSTRAINT FK_PORTFOLIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PORTFOLIO_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);
