-- CREO SCHEMA EN CASO DE QUE NO EXISTA --
CREATE DATABASE IF NOT EXISTS INVESTTRACK;
USE INVESTTRACK;

-- TABLAS BASE --
CREATE TABLE IF NOT EXISTS USUARIOS(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_COMPLETO_USUARIO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS BROKERS(
	ID_BROKER INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_BROKER VARCHAR(50) NOT NULL,
    COMISION_ESTANDAR DECIMAL(5,2)
);

CREATE TABLE IF NOT EXISTS MONEDA(
	ID_MONEDA INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(4) NOT NULL, -- EJ ARS, USD, ETH
    DESCRIPCION VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS SECTORES(
	ID_SECTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_SECTOR VARCHAR(20) NOT NULL
);
-- TABLAS DEPENDIENTES --
CREATE TABLE IF NOT EXISTS ACTIVOS(
	ID_ACTIVO INT PRIMARY KEY AUTO_INCREMENT,
    TICKER VARCHAR(10),
    NOMBRE_ACTIVO VARCHAR(30),
    TIPO_ACTIVO VARCHAR(30),
    ID_SECTOR INT,
    CONSTRAINT FK_ACTIVO_SECTOR FOREIGN KEY (ID_SECTOR) REFERENCES SECTORES(ID_SECTOR)
);
CREATE TABLE IF NOT EXISTS ORDENES_COMPRA_VENTA(
	ID_ORDEN INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ACTIVO INT,
    ID_BROKER INT,
    ID_MONEDA INT,
    CANTIDAD DECIMAL(15,2) NOT NULL,
    PRECIO_UNITARIO DECIMAL(15,2) NOT NULL,
    FECHA_OPERACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIPO_OPERACION ENUM("COMPRA","VENTA"),
    COMISION_PAGADA DECIMAL(5,2),
    CONSTRAINT FK_ORDEN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_ORDEN_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO),
    CONSTRAINT FK_ORDEN_BROKER FOREIGN KEY (ID_BROKER) REFERENCES BROKERS(ID_BROKER),
    CONSTRAINT FK_ORDEN_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID_MONEDA)
);
CREATE TABLE IF NOT EXISTS CAUCIONES_OPERADAS(
	ID_CAUCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    MONTO_COLOCADO DECIMAL(15,2) NOT NULL,
    TASA_NOMINAL_ANUAL DECIMAL(5,2) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    CONSTRAINT FK_CAUCION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
CREATE TABLE IF NOT EXISTS DIVIDENDOS_CUPONES(
	ID_RENTA INT PRIMARY KEY AUTO_INCREMENT, 
    ID_ACTIVO INT,
    MONTO_BRUTO DECIMAL(15,2) NOT NULL,
    IMPUESTOS DECIMAL(15,2) DEFAULT 0,
    MONTO_NETO DECIMAL(15,2) NOT NULL,
    FECHA_COBRO DATE NOT NULL,
    CONSTRAINT FK_RENTA_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);
CREATE TABLE IF NOT EXISTS COTIZACIONES_HISTORICAS(
	ID_PRECIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ACTIVO INT,
    PRECIO_CIERRE DECIMAL(15,2) NOT NULL,
    FECHA_PRECIO DATE NOT NULL,
    CONSTRAINT FK_COTIZACION_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);
CREATE TABLE IF NOT EXISTS PORTFOLIO(
	ID_PORTFOLIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ACTIVO INT, 
    CANTIDAD_TOTAL DECIMAL(15,2),
    ULTIMO_PRECIO DECIMAL(15,2),
    CONSTRAINT FK_PORTFOLIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PORTFOLIO_ACTIVO FOREIGN KEY (ID_ACTIVO) REFERENCES ACTIVOS(ID_ACTIVO)
);
CREATE TABLE IF NOT EXISTS SALDO_DISPONIBLE_BROKERS(
	ID_DISPONIBLE_BROKERS INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_BROKER INT,
    ID_MONEDA INT,
    SALDO_DISPONIBLE DECIMAL (15,2),
    CONSTRAINT FK_DISPONIBLE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_DISPONIBLE_BROKER FOREIGN KEY (ID_BROKER) REFERENCES BROKERS(ID_BROKER),
    CONSTRAINT FK_DISPONIBLE_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID_MONEDA)
);
CREATE TABLE IF NOT EXISTS LOG_OPERACIONES(
    ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
    ACCION ENUM("INSERT", "UPDATE", "DELETE"),
    TABLA_AFECTADA VARCHAR(50),
    USUARIO_ID INT,
    FECHA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- VISTAS --
CREATE OR REPLACE VIEW VW_PORTAFOLIO_DETALLADO AS
    SELECT
		T2.ID_USUARIO,
        T2.NOMBRE_COMPLETO_USUARIO,
        T5.NOMBRE_SECTOR,
        T3.TIPO_ACTIVO,
        T3.TICKER,
        T3.NOMBRE_ACTIVO,
        T1.CANTIDAD_TOTAL,
        T1.ULTIMO_PRECIO,
        (T1.CANTIDAD_TOTAL * T1.ULTIMO_PRECIO) AS VALOR_TOTAL_ACTIVO
    FROM PORTFOLIO T1 
        JOIN USUARIOS T2 ON T1.ID_USUARIO = T2.ID_USUARIO
        JOIN ACTIVOS T3 ON T1.ID_ACTIVO = T3.ID_ACTIVO
        JOIN SECTORES T5 ON T3.ID_SECTOR = T5.ID_SECTOR
    ORDER BY 
        T2.NOMBRE_COMPLETO_USUARIO ASC, 
        T5.NOMBRE_SECTOR DESC, 
        T3.TICKER DESC;

# SELECT * FROM VW_PORTAFOLIO_DETALLADO WHERE ID_USUARIO = "3";

CREATE OR REPLACE VIEW VW_RENTAS_POR_ACTIVO AS
    SELECT 
        T3.TICKER,
        T3.NOMBRE_ACTIVO,
        SUM(T1.MONTO_NETO) AS TOTAL_COBRADO_NETO,
        COUNT(T1.ID_RENTA) AS CANTIDAD_DE_COBROS
    FROM DIVIDENDOS_CUPONES T1
        JOIN ACTIVOS T3 ON T1.ID_ACTIVO = T3.ID_ACTIVO
    GROUP BY T3.TICKER, T3.NOMBRE_ACTIVO;
    
# SELECT * FROM VW_RENTAS_POR_ACTIVO WHERE NOMBRE_ACTIVO = "SPY";

CREATE OR REPLACE VIEW VW_CAUCIONES_VIGENTES AS
    SELECT 
		T2.ID_USUARIO,
        T2.NOMBRE_COMPLETO_USUARIO,
        T1.MONTO_COLOCADO,
        T1.TASA_NOMINAL_ANUAL,
        T1.FECHA_FIN,
        DATEDIFF(T1.FECHA_FIN, CURDATE()) AS DIAS_PARA_EL_VENCIMIENTO
    FROM CAUCIONES_OPERADAS T1
        JOIN USUARIOS T2 ON T1.ID_USUARIO = T2.ID_USUARIO
    WHERE T1.FECHA_FIN >= CURDATE();
    
# SELECT * FROM VW_CAUCIONES_VIGENTES WHERE ID_USUARIO = "12";

CREATE OR REPLACE VIEW VW_CASH_DISPONIBLE AS
    SELECT 
		T2.ID_USUARIO,
        T2.NOMBRE_COMPLETO_USUARIO,
        T3.NOMBRE_BROKER,
        T4.CODIGO AS MONEDA,
        T1.SALDO_DISPONIBLE
    FROM SALDO_DISPONIBLE_BROKERS T1
        JOIN USUARIOS T2 ON T1.ID_USUARIO = T2.ID_USUARIO
        JOIN BROKERS T3 ON T1.ID_BROKER = T3.ID_BROKER
        JOIN MONEDA T4 ON T1.ID_MONEDA = T4.ID_MONEDA;
        
# SELECT * FROM VW_CASH_DISPONIBLE WHERE ID_USUARIO = "";

CREATE OR REPLACE VIEW VW_ANALISIS_COMISIONES AS
    SELECT 
		T2.ID_USUARIO,
        T2.NOMBRE_COMPLETO_USUARIO,
        T3.NOMBRE_BROKER,
        SUM(T1.COMISION_PAGADA) AS TOTAL_COMISIONES_PAGADAS,
        AVG(T1.COMISION_PAGADA) AS COMISION_PROMEDIO_POR_ORDEN
    FROM ORDENES_COMPRA_VENTA T1
        JOIN USUARIOS T2 ON T1.ID_USUARIO = T2.ID_USUARIO
        JOIN BROKERS T3 ON T1.ID_BROKER = T3.ID_BROKER
    GROUP BY T2.NOMBRE_COMPLETO_USUARIO, T3.NOMBRE_BROKER;
    
# SELECT * FROM VW_CASH_DISPONIBLE WHERE ID_USUARIO = "";

-- FUNCIONES --

DELIMITER //

CREATE FUNCTION FN_CALCULAR_INTERES_CAUCION_AUTO(MANUAL_ID_CAUCION INT) 
RETURNS DECIMAL(15,2)
READS SQL DATA
BEGIN
    DECLARE V_MONTO DECIMAL(15,2);
    DECLARE V_TNA DECIMAL(5,2);
    DECLARE V_DIAS INT;
    DECLARE V_INTERESES DECIMAL(15,2);
    SELECT MONTO_COLOCADO, TASA_NOMINAL_ANUAL, DATEDIFF(FECHA_FIN, FECHA_INICIO)
		INTO V_MONTO, V_TNA, V_DIAS
	FROM CAUCIONES_OPERADAS
    WHERE ID_CAUCION = MANUAL_ID_CAUCION;
    SET V_INTERESES = (V_MONTO * (V_TNA / 100) * (V_DIAS / 365));
    RETURN V_INTERESES;
END //

CREATE FUNCTION FN_GET_NOMBRE_BROKER(MANUAL_ID_BROKER INT) 
RETURNS VARCHAR(50)
READS SQL DATA
BEGIN
    DECLARE V_NOMBRE VARCHAR(50);
    SELECT NOMBRE_BROKER 
		INTO V_NOMBRE
    FROM BROKERS
    WHERE ID_BROKER = MANUAL_ID_BROKER;
    RETURN V_NOMBRE;
END //

-- STORE PROCEDURES --

CREATE PROCEDURE SP_ORDENAR_TABLA_DINAMICO(IN NOMBRE_TABLA VARCHAR(50), IN NOMBRE_COLUMNA VARCHAR(50), IN SENTIDO_ORDENAMIENTO VARCHAR(4))
BEGIN
    SET @SENTENCIA = CONCAT('SELECT * FROM ', NOMBRE_TABLA, ' ORDER BY ', NOMBRE_COLUMNA, ' ', SENTIDO_ORDENAMIENTO);
    PREPARE EJECUTAR FROM @SENTENCIA;
    EXECUTE EJECUTAR;
    DEALLOCATE PREPARE EJECUTAR;
END //

CREATE PROCEDURE SP_INSERTAR_ACTIVO(
    IN V_TICKER VARCHAR(10), 
    IN V_NOMBRE VARCHAR(30), 
    IN V_TIPO VARCHAR(30), 
    IN MANUAL_ID_SECTOR INT
)
BEGIN
    INSERT INTO ACTIVOS (TICKER, NOMBRE_ACTIVO, TIPO_ACTIVO, ID_SECTOR)
    VALUES (V_TICKER, V_NOMBRE, V_TIPO, MANUAL_ID_SECTOR);
    SELECT CONCAT('Activo ', V_TICKER, ' insertado con éxito') AS resultado;
END //

-- TRIGGERS --

CREATE TRIGGER TR_ACTUALIZAR_PORTFOLIO_AFTER_INSERT
AFTER INSERT ON ORDENES_COMPRA_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO PORTFOLIO (ID_USUARIO, ID_ACTIVO, CANTIDAD_TOTAL, ULTIMO_PRECIO)
    VALUES (
        NEW.ID_USUARIO, 
        NEW.ID_ACTIVO, 
        CASE WHEN NEW.TIPO_OPERACION = 'COMPRA' THEN NEW.CANTIDAD ELSE -NEW.CANTIDAD END, 
        NEW.PRECIO_UNITARIO
    )
    ON DUPLICATE KEY UPDATE 
        CANTIDAD_TOTAL = CASE 
            WHEN NEW.TIPO_OPERACION = 'COMPRA' THEN CANTIDAD_TOTAL + NEW.CANTIDAD 
            ELSE CANTIDAD_TOTAL - NEW.CANTIDAD 
        END,
        ULTIMO_PRECIO = NEW.PRECIO_UNITARIO;
END //

CREATE TRIGGER TR_LOG_AUDITORIA_ORDENES_AFTER_INSERT
AFTER INSERT ON ORDENES_COMPRA_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO LOG_OPERACIONES (ACCION, TABLA_AFECTADA, USUARIO_ID, FECHA_HORA)
    VALUES ('INSERT', 'ORDENES_COMPRA_VENTA', NEW.ID_USUARIO, CURRENT_TIMESTAMP);
END //

DELIMITER ;